name: News Ingest

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ingest script to Firestore
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          if [ -z "${FIREBASE_SERVICE_ACCOUNT}" ]; then
            echo "Missing secret FIREBASE_SERVICE_ACCOUNT" >&2
            exit 1
          fi
          node scripts/ingest.js

      - name: Generate daily PDF (last 24h)
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          if [ -z "${FIREBASE_SERVICE_ACCOUNT}" ]; then
            echo "Missing secret FIREBASE_SERVICE_ACCOUNT" >&2
            exit 1
          fi
          node scripts/export-pdf.js

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-pdf-${{ github.run_id }}
          path: exports/*.pdf

      - name: Export JSON (last 24h)
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          if [ -z "${FIREBASE_SERVICE_ACCOUNT}" ]; then
            echo "Missing secret FIREBASE_SERVICE_ACCOUNT" >&2
            exit 1
          fi
          node scripts/export-json.js

      - name: Publish JSON/PDF to docs for GitHub Pages
        run: |
          mkdir -p docs/data docs/reports
          cp -f exports/*.json docs/data/ || true
          cp -f exports/*.pdf docs/reports/ || true
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/data docs/reports
          git commit -m "chore: daily exports $(date -u +%F)" || echo "No changes to commit"
          git push
